#Create user

POST http://localhost:4000/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "pro51@gmail.com",
  "password": "test123",
  "name": "Владислав",
  "type": "pro"
}

###

#Login user

POST http://localhost:4000/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "pro5@gmail.com",
  "password": "test123"
}

###

# Download avatar

POST http://localhost:4000/users/6921d413f37624f127318b75/avatar HTTP/1.1
Content-Type: application/json

###
